import { Metadata } from "next";
import UserAndZustand from "./UserAndZustand";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function Home() {
    // const abortController = new AbortController();
    // setTimeout(() => {
    //   abortController.abort();
    // }, 2500);

    // await fetch('https://dummyjson.com/products/category-list',{
    //   method: 'GET',
    //   signal: abortController.signal,
    // })
    // .then(res => res.json())
    // .then(data => {
    //   console.log(data);
    // });

    return (
        <>
            <UserAndZustand />
        </>
    );
}
