import { Metadata } from "next";
import UserAndZustand from "./UserAndZustand";
import { useBearStore } from "@/store/Bear.store";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function Home() {
    const { bears } = useBearStore.getState();

    // const abortController = new AbortController();
    // setTimeout(() => {
    //   abortController.abort();
    // }, 2500);

    // await fetch('https://dummyjson.com/products/category-list',{
    //   method: 'GET',
    //   signal: abortController.signal,
    // })
    // .then(res => res.json())
    // .then(data => {
    //   console.log(data);
    // });

    return (
        <>
            <UserAndZustand />
            <div className="flex flex-col w-screen justify-center items-center p-10">
                <h1>Valor do zustand store dentro de server component</h1>
                <strong>{bears}</strong>
            </div>
        </>
    );
}
